### ISSUE TITLE
Curate this list for people to know about Singapore

### ISSUE THREAD

**Issue by JuanitoFatas** [rubysg/awesome-singapore#1]
Background: https://github.com/sindresorhus/awesome/issues/153

**Comment by winston** [comment]
Not sure if we need this, since @sayanee is already maintaining some lists over at webuild.sg.

**Comment by sayanee** [comment]
:+1: checkout https://webuild.sg/ - always fresh and updating, no stale static list 😁

**Comment by winston** [comment]
@JuanitoFatas can we close this repo?

**Comment by JuanitoFatas** [comment]
OK! I will update with them. Closing this repo.
